1. Escribe la función `suma_producto` que tome un numpy array con dos dimensiones de shape `(n, n)`, el índice de una fila, el índice de una columna, y calcule la suma de multiplicar cada elemento de la columna seleccionada por cada elemento de la fila seleccionada.

Por ejemplo, te tener una matriz
```
a1 = np.array([[2, 3, 3],
               [4, 3, 3],
               [5, 3, 1]])
```

Calcular ```suma_producto(a1, 0, 2)``` consideraría la primera fila (`[2, 3, 3]`), la última columna (`[3, 3, 1]`)  y realizaría la siguiente operación:
```
2 * 3 + 3 * 3 + 3 * 1 = 18
```

```python
>>> a2 = np.array([2, 3,
                   3, 4])
>>> suma_producto(a2, 0, 0)
13

a3 = np.array([[2, 3, 3, 4],
               [3, 3, 5, 3],
               [1, 2, 2, 3],
               [5, 5, 5, 5]])
>>> suma_producto(a3, 2, 1)
28

```

In [28]:
def suma_producto(a, ixrow, ixcol):
    return (a[ixrow, :] * a[:, ixcol]).sum()

2. escribe la función (`suma_pos`) que tome un numpy array y regrese la suma de todos los elementos positivos del array

```python
>>> a1 = np.array([[ 0,  4,  1],
                   [-3, -3,  1],
                   [-3,  2, -3]])
>>> suma_pos(a1)
8
```

In [164]:
def suma_pos(arr):
    return arr[arr > 0].sum()

3. Escribe la función `cercano` que tome un numpy array unidimensional, un número base y encuentre el (los) número(s) que más se aproxime (en valor aboluto) al número base

```python
a1 = np.arrray([-25,  27,   8, -12,  20,   8,  29, -28,   9, -12, -23, -26,  20,-22, -29])
>>> cercano(a1, 10)
array([9])
>>> cercano(a1, -3)
array([-12, -12])
```

In [197]:
def cercano(arr, obj):
    diff = np.abs(arr - obj)
    return arr[np.where(diff == diff.min())]

4. Escribe la función `computesto(capital, r, years, filename)` que tome un capital inicial `capital`, una tasa de interés real `r`, un número de años `years`, el nombre de un archivo `filename` y cree un archivo con `years` filas de la siguiente forma: `t={y:02} | C={amount:02f}`; donde `y` es el año en cuestión y `amount` es el valor de la inversión al año `y`.

Por ejemplo:
```python
compuesto(100, 0.03, 5, "comp.txt")
```

Deberá crear un archivo `comp.txt` con la siguiente información:
```
t=00 | C=100.00
t=01 | C=103.00
t=02 | C=106.09
t=03 | C=109.27
t=04 | C=112.55
t=05 | C=115.93
```

In [207]:
def compuesto(capital, r, years, filename):
    with open(filename, "w") as f:
        for y in range(years + 1):
            amount = capital * (1 + r) ** y
            row = f"t={y:02} | C={amount:0.2f}\n"
            f.write(row)

5. Escribe un programa `filter_sum(arr, stride)` que cree un _filtro_ de suma para un numpy array de dos dimensiones con `arr.shape[0] == arr.shape[1]`. Un filtro de tamaño `stride` captura los elementos de `arr` con una _ventana_ de tamaño `(stride, stride)` y suma los valores para arrojar un nuevo resultado dentro de una matriz final.

Por ejemplo, dado el array
```
[[ 6,  7, 19, 19,  7],
[ 3,  8, 19,  8,  5],
[19,  9,  2, 11, 15],
[ 5, 15,  6, 17, 17],
[17,  2,  1, 17, 12]]
```

Las _ventanas_ de la matriz serían
```
[[ 6  7 19]
 [ 3  8 19]
 [19  9  2]]

[[ 7 19 19]
 [ 8 19  8]
 [ 9  2 11]]
 
 ...
 
 [[ 2 11 15]
 [ 6 17 17]
 [ 1 17 12]]
```

Con valores `92, 105, ..., 98`

y la matriz resultante sería

```
[[ 92., 102., 105.],
[ 86.,  95., 100.],
[ 76.,  80.,  98.]])
```

In [306]:
def filter_sum(arr, stride):
    arr_el = arr.shape[0]
    filter_size = arr_el // stride + 2
    new_arr = np.zeros((filter_size, filter_size))
    for ypos in range(filter_size):
        for xpos in range(filter_size):
            fpixel = arr[ypos:stride*1 + ypos, xpos:stride*1 + xpos]
            print(fpixel,end="\n\n")
            new_arr[ypos, xpos] = fpixel.sum()

    return new_arr