# Examen Final
## Universidad Marista
### Introducción a la Computación I

1. Escribe la función `suma_division` que tome un numpy array con dos dimensiones de shape `(n, n)`, el índice de una fila, el índice de una columna, y calcule la suma de dividir cada elemento de la columna seleccionada por cada elemento de la fila seleccionada.

Por ejemplo, de tener una matriz
```
a1 = np.array([[2, 3, 3],
               [4, 3, 3],
               [5, 3, 1]])
```

Calcular ```suma_division(a1, 0, 2)``` consideraría la primera fila (`[2, 3, 3]`), la última columna (`[3, 3, 1]`)  y realizaría la siguiente operación:
```
2 / 3 + 3 / 3 + 3 / 1 = 4.6666
```

```python
>>> a2 = np.array([[2, 3],
                   [3, 4]])
>>> suma_division(a2, 0, 0)
2.0

a3 = np.array([[2, 3, 3, 4],
               [3, 3, 5, 3],
               [1, 2, 2, 3],
               [5, 5, 5, 5]])
>>> suma_division(a3, 2, 1)
2.6
```

2. escribe la función (`suma_pos`) que tome un numpy array y regrese la suma de todos los elementos positivos del array

```python
>>> a1 = np.array([[ 0,  4,  1],
                   [-3, -3,  1],
                   [-3,  2, -3]])
>>> suma_neg(a1)
-12
```

3. Escribe la función `cercano` que tome un numpy array unidimensional, un número base y encuentre el (los) número(s) que más se aproxime (en valor aboluto) al número base

```python
a1 = np.arrray([-25,  27,   8, -12,  20,   8,  29, -28,   9, -12, -23, -26,  20,-22, -29])
>>> cercano(a1, 10)
array([9])
>>> cercano(a1, -3)
array([-12, -12])
```

4. Escribe la función `valoresf(f, xmin, xmax, filename, pasos=1)` que tome una función `f` y cree un archivo llamado `filename` dónde se muestren los valores de `f` evaluados desde `f(xmin)` hasta `f(xmax)` tomando pasos de tamaño `pasos`.

Por ejemplo:
```python
def f(x): return x**2

valoresf(f, -2, 2, "fx2.txt", pasos=0.5)
```

Deberá crear un archivo `fx2.txt` con la siguiente información **y formato**:
```
f(-2.000) = 4.000
f(-1.500) = 2.250
f(-1.000) = 1.000
f(-0.500) = 0.250
f(0.000) = 0.000
f(0.500) = 0.250
f(1.000) = 1.000
f(1.500) = 2.250
f(2.000) = 4.000
```

5. Escribe un programa `filter_max(arr, stride)` que cree un _filtro_ de suma para un numpy array de dos dimensiones con `arr.shape[0] == arr.shape[1]`. Un filtro de tamaño `f` captura los elementos de `arr` con una _ventana_ de tamaño `(f, f)` y suma los valores para arrojar un nuevo resultado dentro de una matriz final.

Por ejemplo, dado el array
```
[[ 6,  7, 19, 19,  7],
[ 3,  8, 19,  8,  5],
[19,  9,  2, 11, 15],
[ 5, 15,  6, 17, 17],
[17,  2,  1, 17, 12]]
```

Las _ventanas_ de la matriz (con `f=3`) serían
```
[[ 6  7 19]
 [ 3  8 19]
 [19  9  2]]

[[ 7 19 19]
 [ 8 19  8]
 [ 9  2 11]]
 
 ...
 
 [[ 2 11 15]
 [ 6 17 17]
 [ 1 17 12]]
```

Con valores `19, 19, ..., 17`

y la matriz resultante sería

```
[[19., 19., 19.],
[19., 19., 19.],
[19., 17., 17.]]
```

### Extra
1. ¿Cuáles son las propiedades de un numpy array?
2. ¿En qué ocasiones ocuparías un numpy array o una lista? ¿Cuál es la ventaja de ocupar un numpy array?
3. Dado un numpy array `arr`, ¿de qué manera reescribirías el siguiente código usando los métodos de un numpy array? `[2 * a ** 2 for a in arr if -10 < a < 10]`
4. Crea una gráfica de las funciones $f(x) = \sin(x)$ y $g(x) = \cos(x)$ entre $x \in [0, 2\pi]$